function ConfigurableParameters = getAlgConfigurableParameters_ACFPSO()
    % PopulationSize: Number of particles in each sub‑swarm.
    ConfigurableParameters.PopulationSize = struct( ...
        'value', 5, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of particles in each sub‑swarm.');

    % x: Inertia weight used in velocity update.
    ConfigurableParameters.x = struct( ...
        'value', 0.729843788, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Inertia weight controlling the influence of previous velocity.');

    % c1: Cognitive coefficient influencing personal best attraction.
    ConfigurableParameters.c1 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Cognitive acceleration coefficient scaling attraction toward personal best.');

    % c2: Social coefficient influencing global best attraction.
    ConfigurableParameters.c2 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Social acceleration coefficient scaling attraction toward social best.');

    % ConvergenceSleepLayer: diversity threshold factor to trigger sleep phase.
    ConfigurableParameters.ConvergenceSleepLayer = struct( ...
        'value', 0.05, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Diversity threshold factor below which a sub‑swarm enters sleep phase.');

    % ConvergenceOuterLayer: diversity threshold factor for exploiter phase.
    ConfigurableParameters.ConvergenceOuterLayer = struct( ...
        'value', 0.8, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Diversity threshold factor (relative to Radius) for exploiter phase.');

    % ConvergenceInnerLayer: diversity threshold factor for tracker phase.
    ConfigurableParameters.ConvergenceInnerLayer = struct( ...
        'value', 0.3, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Diversity threshold factor (relative to Radius) for tracker phase.');

    % ExclusionOuterLayer: outer exclusion boundary factor.
    ConfigurableParameters.ExclusionOuterLayer = struct( ...
        'value', 1, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Radius factor defining the outer exclusion area between sub‑swarms.');

    % ExclusionInnerLayer: inner exclusion boundary factor.
    ConfigurableParameters.ExclusionInnerLayer = struct( ...
        'value', 0.3, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Radius factor defining the inner exclusion area between sub‑swarms.');
end
