function ConfigurableParameters = getAlgConfigurableParameters_mDE()
    % PopulationSize: Number of individuals per subpopulation.
    ConfigurableParameters.PopulationSize = struct( ...
        'value', 5, ...
        'type', 'integer', ...
        'range', [1, 100], ...
        'description', 'Number of individuals per subpopulation.');
end