function ConfigurableParameters = getAlgConfigurableParameters_DSPSO()
    % PopulationSize: Total number of particles in the swarm.
    ConfigurableParameters.PopulationSize = struct( ...
        'value', 100, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Total number of particles across all species.');

    % x: Inertia weight used in velocity updates.
    ConfigurableParameters.x = struct( ...
        'value', 0.729843788, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Inertia weight balancing influence of previous velocity.');

    % c1: Cognitive coefficient influencing personal best attraction.
    ConfigurableParameters.c1 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Scaling factor for movement toward each particle’s personal best.');

    % c2: Social coefficient influencing local best (lbest) attraction.
    ConfigurableParameters.c2 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Scaling factor for movement toward the best of its species.');

    % Radius: Distance threshold for forming species clusters.
    ConfigurableParameters.Radius = struct( ...
        'value', 30, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Max distance between personal bests to group particles into a species.');

    % Pmax: Maximum active particles per species.
    ConfigurableParameters.Pmax = struct( ...
        'value', 10, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Upper limit on active individuals retained in each species.');
end
