function ConfigurableParameters = getAlgConfigurableParameters_CESO()
    % PopulationSizeSwarm: Number of particles in the main PSO-based swarm, the PSO-based size must be equal or smaller than the CRDE size.
    ConfigurableParameters.PopulationSizeSwarm = struct( ...
        'value', 10, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of particles in the PSO-based swarm. Must not exceed the CRDE population size.');

    % PopulationSizeCRDE: Number of individuals in the DE-based subpopulation
    ConfigurableParameters.PopulationSizeCRDE = struct( ...
        'value', 10, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of individuals in the DE-based population (CRDE). Should be ≥ swarm size.');

    % x: Inertia weight applied in PSO velocity update
    ConfigurableParameters.x = struct( ...
        'value', 0.729843788, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Inertia weight used to balance exploration and exploitation in PSO.');

    % c1: Cognitive acceleration coefficient in PSO
    ConfigurableParameters.c1 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Coefficient for particle’s personal best guidance in PSO.');

    % c2: Social acceleration coefficient in PSO
    ConfigurableParameters.c2 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Coefficient for global best guidance in PSO.');

    % theta: Distance threshold for knowledge transfer between populations
    ConfigurableParameters.theta = struct( ...
        'value', 1, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Threshold for transferring best solution between CRDE and swarm populations.');

    % CR: Crossover probability in CRDE evolution
    ConfigurableParameters.CR = struct( ...
        'value', 0.9, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Probability of applying crossover in CRDE differential evolution process.');

    % F: Scaling factor in CRDE mutation
    ConfigurableParameters.F = struct( ...
        'value', 0.5, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Differential mutation scaling factor in CRDE.');

    % Vmax: Upper bound for velocity in PSO
    ConfigurableParameters.Vmax = struct( ...
        'value', 0.1, ...
        'type', 'numeric', ...
        'range', [-10, 10], ...
        'description', 'Maximum allowed velocity value for particles in PSO.');

    % Vmin: Lower bound for velocity in PSO
    ConfigurableParameters.Vmin = struct( ...
        'value', -0.1, ...
        'type', 'numeric', ...
        'range', [-10, 10], ...
        'description', 'Minimum allowed velocity value for particles in PSO.');
end
