function ConfigurableParameters = getAlgConfigurableParameters_mCMAES()
    % PopulationSize: Number of individuals per CMA-ES swarm.
    ConfigurableParameters.PopulationSize = struct( ...
        'value', 1, ...
        'type', 'integer', ...
        'range', [1, 100], ...
        'description', 'Number of individuals per CMA-ES sub-swarm.');
end