function ConfigurableParameters = getAlgConfigurableParameters_CPSO()
    % CPSO algorithm configurable parameters

    % initPopulationSize: Total number of particles at initialization.
    ConfigurableParameters.initPopulationSize = struct( ...
        'value', 100, ...
        'type', 'integer', ...
        'range', [0, 1000], ...
        'description', 'Total number of particles at initialization.');

    % maxSubsize: Maximum allowable size of any sub‑swarm before trimming.
    ConfigurableParameters.maxSubsize = struct( ...
        'value', 5, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Maximum number of particles retained in a sub‑swarm to prevent overcrowding.');

    % w: Inertia weight balancing exploration and exploitation.
    ConfigurableParameters.w = struct( ...
        'value', 0.6, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Inertia weight applied to previous velocity in PSO update.');

    % c1: Cognitive acceleration coefficient.
    ConfigurableParameters.c1 = struct( ...
        'value', 1.7, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Coefficient scaling the influence of the particle’s personal best.');

    % c2: Social acceleration coefficient.
    ConfigurableParameters.c2 = struct( ...
        'value', 1.7, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Coefficient scaling the influence of the sub‑swarm’s global best.');

    % ConvergenceLimit: Radius threshold to declare a sub‑swarm converged.
    ConfigurableParameters.ConvergenceLimit = struct( ...
        'value', 0.0001, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Radius below which a sub‑swarm is considered converged.');

    % OverlapDegree: Threshold proportion for sub‑swarm overlap detection.
    ConfigurableParameters.OverlapDegree = struct( ...
        'value', 0.7, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Fraction of overlapping particles required to trigger sub‑swarm merge or removal.');
end
