function ConfigurableParameters = getAlgConfigurableParameters_AMPDE()
    % initPopulationSize: Total number of individuals at initialization.
    ConfigurableParameters.initPopulationSize = struct( ...
        'value', 100, ...
        'type', 'integer', ...
        'range', [0, 1000], ...
        'description', 'Total number of individuals at initialization.');

    % CR: Crossover rate for generating trial vectors.
    ConfigurableParameters.CR = struct( ...
        'value', 0.6, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Crossover probability used to mix donor and target vectors.');

    % F: Differential weight for mutation step.
    ConfigurableParameters.F = struct( ...
        'value', 0.5, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Scaling factor controlling the influence of difference vectors in mutation.');

    % ConvergenceLimit: Radius threshold to determine hibernation.
    ConfigurableParameters.ConvergenceLimit = struct( ...
        'value', 0.00001, ...
        'type', 'numeric', ...
        'range', [0, 0.1], ...
        'description', 'Sub‑swarm radius below which it is considered converged (hibernated).');

    % OverlapDegree: Proportion threshold for sub‑swarm overlap detection.
    ConfigurableParameters.OverlapDegree = struct( ...
        'value', 0.1, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Proportion of individuals that must overlap to trigger sub‑swarm removal.');

    % diversityFactor: Factor for diversity‐based activation threshold.
    ConfigurableParameters.diversityFactor = struct( ...
        'value', 0.005, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Factor used to scale domain size for diversity-based activation of sub‑swarms.');

    % StepIndivs: Base step for population size adjustment.
    ConfigurableParameters.StepIndivs = struct( ...
        'value', 10, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Base number of individuals used as a unit when increasing diversity.');    
end
