function ConfigurableParameters = getAlgConfigurableParameters_FTMPSO()
    % PopulationSize: Number of particles in each tracker sub‑swarm.
    ConfigurableParameters.PopulationSize = struct( ...
        'value', 5, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of particles maintained in each tracker sub‑swarm.');

    % x: Inertia weight used in velocity update.
    ConfigurableParameters.x = struct( ...
        'value', 0.729843788, ...
        'type', 'numeric', ...
        'range', [0, 2], ...
        'description', 'Inertia weight balancing exploration and exploitation.');

    % c1: Cognitive coefficient influencing personal best attraction.
    ConfigurableParameters.c1 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Scaling factor for attraction toward each particle''s personal best.');

    % c2: Social coefficient influencing global best attraction.
    ConfigurableParameters.c2 = struct( ...
        'value', 2.05, ...
        'type', 'numeric', ...
        'range', [0, 5], ...
        'description', 'Scaling factor for attraction toward each sub‑swarm''s global best.');

    % P: Fraction of the Finder Gbest history window used for convergence detection.
    ConfigurableParameters.P = struct( ...
        'value', 0.5, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Fraction of the Finder''s best‑position history length considered when checking convergence.');

    % Q: Initial cloud radius as a fraction of the search domain for local search.
    ConfigurableParameters.Q = struct( ...
        'value', 0.5, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Initial radius (as fraction of variable range) for local search around the best tracker.');

    % SleepingLimit: Velocity threshold below which a tracker is put to sleep.
    ConfigurableParameters.SleepingLimit = struct( ...
        'value', 0.4, ...
        'type', 'numeric', ...
        'range', [0, 1], ...
        'description', 'Absolute velocity below which a tracker is considered idle and put to sleep.');

    % CFmin: Minimum cloud‑shrink factor for the local search radius update.
    ConfigurableParameters.CFmin = struct( ...
        'value', 0.8, ...
        'type', 'numeric', ...
        'range', [0, 10], ...
        'description', 'Lower bound on the factor that shrinks the local search cloud radius each update.');

    % TryNumber: Number of random local‑search probes around the best tracker.
    ConfigurableParameters.TryNumber = struct( ...
        'value', 20, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of random samples generated around the best tracker during local search.');

    % FinderPopulationSize: Number of particles in the Finder swarm.
    ConfigurableParameters.FinderPopulationSize = struct( ...
        'value', 10, ...
        'type', 'integer', ...
        'range', [0, 100], ...
        'description', 'Number of particles maintained in the Finder swarm used to locate new peaks.');

end
